In [ ]:
'''Используем файл keywords.csv.

Необходимо написать гео-классификатор, 
который каждой строке сможет выставить географическую принадлежность определенному региону. 
Т. е. если поисковый запрос содержит название города региона, 
то в столбце ‘region’ пишется название этого региона. 
Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {

1 'Центр': ['москва', 'тула', 'ярославль'],
2
3 'Северо-Запад': ['петербург', 'псков', 'мурманск'],
4
5 'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']

}

Результат классификации запишите в отдельный столбец region.'''

In [1]:
import pandas as pd

In [4]:
keywords = pd.read_csv('ml-latest-small/keywords.csv')
keywords.head(10)

                      keyword     shows
0                          вк  64292779
1               одноклассники  63810309
2                       порно  41747114
3                        ютуб  39995567
4                   вконтакте  21014195
5  одноклассники моя страница  19976138
6                        майл  15144673
7                       авито  14786593
8                  переводчик  14453469
9                      яндекс  13344734

In [31]:
geo_data = {
    
    'Центр': ['москва', 'тула', 'ярославль'],
    
    'Северо-Запад': ['петербург', 'псков', 'мурманск'],
    
    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
    
    }

In [105]:
def region(keyword):
    for regions, cities in geo_data.items():
        for city in cities:
            if city in keyword:
                return regions
            
    return 'undefined'

region('тула')

'Центр'

In [101]:
keywords['region'] = keywords['keyword'].apply(region)
keywords

                       keyword     shows     region
0                           вк  64292779  undefined
1                одноклассники  63810309  undefined
2                        порно  41747114  undefined
3                         ютуб  39995567  undefined
4                    вконтакте  21014195  undefined
...                        ...       ...        ...
99995   эльдорадо старый оскол      3705  undefined
99996      frigate для firefox      3630  undefined
99997                   укрсиб      3630  undefined
99998  погода в ялте на неделю      3688  undefined
99999                     ггму      3630  undefined

[100000 rows x 3 columns]

In [102]:
center = keywords[(keywords['region'] == 'Центр')]
center

                                                keyword   shows region
127                                        авито москва  979292  Центр
849                                     авито ярославль  209581  Центр
1259                                             москва  153050  Центр
1396                                    гисметео москва  140279  Центр
1482                                   госуслуги москва  133061  Центр
...                                                 ...     ...    ...
98943  вакансии на авито москва от прямых работодателей    3738  Центр
99292                      афиша кино москва на сегодня    3704  Центр
99590             авито ярославль автомобили с пробегом    3673  Центр
99890                               яндекс метро москва    4548  Центр
99922                                 авто ру ярославль    3712  Центр

[387 rows x 3 columns]

In [103]:
sz = keywords[(keywords['region'] == 'Северо-Запад')]
sz

                                                 keyword   shows        region
370                             авито ру санкт петербург  425134  Северо-Запад
564                            погода в санкт петербурге  292489  Северо-Запад
1236                                банк санкт петербург  174375  Северо-Запад
1346                                     санкт петербург  144232  Северо-Запад
2121   электронный дневник санкт петербургского образ...   94835  Северо-Запад
...                                                  ...     ...           ...
99084   122 медсанчасть санкт петербург официальный сайт    3679  Северо-Запад
99134     росреестр по санкт петербургу официальный сайт    3700  Северо-Запад
99204                         bileter ru санкт петербург    3661  Северо-Запад
99634               северпост новости мурманской области    3606  Северо-Запад
99808                  полармед мурманск запись на прием    3719  Северо-Запад

[266 rows x 3 columns]

In [104]:
dv = keywords[(keywords['region'] == 'Дальний Восток')]
dv

                                       keyword   shows          region
1063                       фарпост владивосток  176951  Дальний Восток
2175                            дром хабаровск   98361  Дальний Восток
3206                          дром владивосток   73084  Дальний Восток
3275                        100 сп владивосток   76418  Дальний Восток
3687                           авито хабаровск   63736  Дальний Восток
...                                        ...     ...             ...
90402                     аэропорт владивосток    4658  Дальний Восток
92442  монастырев владивосток официальный сайт    3870  Дальний Восток
92843                    проститутки хабаровск    4120  Дальний Восток
93872                        биглион хабаровск    3890  Дальний Восток
95572                 точное время владивосток    4142  Дальний Восток

[94 rows x 3 columns]