In [ ]:
'''Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):
https://fortrader.org/quotes
https://www.finanz.ru/valyuty/v-realnom-vremeni'''

In [1]:
import pandas as pd

In [5]:
page_url_fortrader = 'https://fortrader.org/quotes'

In [14]:
df_fortrader = pd.read_html(page_url_fortrader, encoding='utf-8')[3]

In [18]:
df_fortrader.head(10)

,Название,Цена,Изменение,Изменение(%),Обновлено
0,ВТБ Акции ВТБ,0.038980,0.000195,0.502772,NaN
1,Газпром Акции газпрома,226.81,-1.930000,-0.840000,NaN
2,Лукойл Акции Лукойл,6 195.5,-62.000000,-1.000000,NaN
3,Роснефть Акции Роснефти,572.75,-2.550000,-0.440000,NaN
4,Сбербанк Акции Сбербанка,292.35,-0.950000,-0.320000,NaN
5,Сургутнефтегаз Акции Сургутнефтегаза,34.830,-0.055000,-0.158000,NaN
6,Норникель Акции Норникель,22 900,-216.000000,-1.000000,NaN
7,Аэрофлот Акции Аерофлота,66.38,-1.080000,-1.600000,NaN
8,Северсталь Акции Северсталь,1 470.40,29.200000,2.030000,NaN
9,Транснефть Акции Транснефть,150 900,350.000000,0.000000,NaN

In [19]:
page_url_finanz = 'https://www.finanz.ru/valyuty/v-realnom-vremeni'

In [23]:
df_finanz = pd.read_html(page_url_finanz, encoding='utf-8')[1]

In [24]:
df_finanz.head(10)

,Unnamed: 0,Рубль,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
0,NaN,GBP/RUB,1044084,-,1041667,"0,23 %",02418,12:58:00
1,NaN,EUR/RUB,891007,-,890645,"0,04 %",00362,12:58:00
2,NaN,USD/RUB,758870,-,756695,"0,29 %",02175,12:58:00
3,NaN,JPY/RUB,06883,-,06892,"-0,13 %",-00009,12:58:00
4,NaN,CNY/RUB,115559,-,115205,"0,31 %",00354,12:58:00
5,NaN,CHF/RUB,805485,-,805856,"-0,05 %",-00371,12:58:00
6,NaN,Евро,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
7,NaN,EUR/USD,11741,-,11769,"-0,23 %",-00028,12:58:00
8,NaN,EUR/GBP,08532,-,08550,"-0,21 %",-00018,12:58:00
9,NaN,EUR/JPY,1294300,-,1292400,"0,15 %",01900,12:58:00